version: '3'

services:
    cfgsvr1:
        container_name: cfgsvr1
        image: mongo
        command: mongod --configsvr --replSet cfgrs --port 27017 --dbpath /data/db
        ports:
            - 40001:27017
        volumes:
            - cfgsvr1:/data/db

    shardsvr1:
        container_name: shardsvr1
        image: mongo
        command: mongod --shardsvr --replSet shardrs --port 27017 --dbpath /data/db
        ports:
            - 50001:27017
        volumes:
            - shardsvr1:/data/db
    

volumes:
  cfgsvr1: {}
  shardsvr1: {}